import Foundation
import SwiftData

/// Represents a suggested or applied change to an exercise prescription.
///
/// **Sources:**
/// - `.rules`: Generated by rule engine
/// - `.ai`: Generated by Apple FoundationModels
/// - `.user`: Manual user edit
///
/// **Lifecycle:**
/// 1. Created with `decision = .pending`
/// 2. User reviews: Sets `decision` to `.accepted`, `.rejected`, or `.deferred`
/// 3. After next workout: `outcome` determined (`.good`, `.tooAggressive`, `.tooEasy`, `.ignored`, or `.userModified`)
/// 4. `outcomeReason` explains WHY (for learning)
///
/// **Learning:**
/// - Query by `catalogID` + `changeType` to see success patterns
/// - `outcomeReason` provides AI/rule reasoning for future suggestions
/// - `targetPlan` tracks context (same exercise, different plans may progress differently)
@Model
final class PrescriptionChange {
    #Index<PrescriptionChange>([\.catalogID], [\.createdAt])

    var id: UUID = UUID()
    var source: SuggestionSource = SuggestionSource.rules
    var catalogID: String = ""
    
    // When/where triggered
    @Relationship(deleteRule: .nullify, inverse: \WorkoutSession.createdPrescriptionChanges)
    var sessionFrom: WorkoutSession?
    var createdAt: Date = Date()              // When suggestion was created
    
    // Evidence (what led to this suggestion)
    @Relationship(deleteRule: .nullify, inverse: \ExercisePerformance.sourceChanges)
    var sourceExercisePerformance: ExercisePerformance?
    @Relationship(deleteRule: .nullify, inverse: \SetPerformance.sourceChanges)
    var sourceSetPerformance: SetPerformance?
    
    // Target (what prescription this affects)
    @Relationship(deleteRule: .nullify)
    var targetExercisePrescription: ExercisePrescription?
    @Relationship(deleteRule: .nullify)
    var targetSetPrescription: SetPrescription?
    var targetPlan: WorkoutPlan?              // Which plan (context matters)
    
    // The Change
    var changeType: ChangeType = ChangeType.increaseWeight
    var previousValue: Double?
    var newValue: Double?
    var changeReasoning: String?              // Why suggest this change
    var trainingStyle: TrainingStyle?
    
    // Decision (user choice)
    var decision: Decision = Decision.pending
    
    // Outcome (how it went)
    var outcome: Outcome = Outcome.pending
    var outcomeReason: String?                // WHY this outcome (for learning)
    @Relationship(deleteRule: .nullify, inverse: \WorkoutSession.evaluatedPrescriptionChanges)
    var evaluatedInSession: WorkoutSession?   // Which session evaluated
    var evaluatedAt: Date?                    // When outcome was determined
    
    init() {}

    // Test/sample initializer to reduce setup boilerplate.
    convenience init(source: SuggestionSource = .rules, catalogID: String = "", sessionFrom: WorkoutSession? = nil, createdAt: Date = Date(), sourceExercisePerformance: ExercisePerformance? = nil, sourceSetPerformance: SetPerformance? = nil, targetExercisePrescription: ExercisePrescription? = nil, targetSetPrescription: SetPrescription? = nil, targetPlan: WorkoutPlan? = nil, changeType: ChangeType = .increaseWeight, previousValue: Double? = nil, newValue: Double? = nil, changeReasoning: String? = nil, trainingStyle: TrainingStyle? = nil, decision: Decision = .pending, outcome: Outcome = .pending, outcomeReason: String? = nil, evaluatedInSession: WorkoutSession? = nil, evaluatedAt: Date? = nil) {
        self.init()
        self.source = source
        self.catalogID = catalogID
        self.sessionFrom = sessionFrom
        self.createdAt = createdAt
        self.sourceExercisePerformance = sourceExercisePerformance
        self.sourceSetPerformance = sourceSetPerformance
        self.targetExercisePrescription = targetExercisePrescription
        self.targetSetPrescription = targetSetPrescription
        self.targetPlan = targetPlan
        self.changeType = changeType
        self.previousValue = previousValue
        self.newValue = newValue
        self.changeReasoning = changeReasoning
        self.trainingStyle = trainingStyle
        self.decision = decision
        self.outcome = outcome
        self.outcomeReason = outcomeReason
        self.evaluatedInSession = evaluatedInSession
        self.evaluatedAt = evaluatedAt
    }
}

// MARK: - Fetch Descriptors

extension PrescriptionChange {
    /// Pending or deferred suggestions for a plan (for pre-workout review).
    static func pendingOrDeferred(forPlanID planID: UUID) -> FetchDescriptor<PrescriptionChange> {
        let pending = Decision.pending
        let deferred = Decision.deferred
        let predicate = #Predicate<PrescriptionChange> { change in
            change.targetPlan?.id == planID && (change.decision == pending || change.decision == deferred)
        }
        return FetchDescriptor(predicate: predicate)
    }

    /// Changes with pending outcome for a plan (for cleanup on plan deletion).
    static func pendingOutcome(forPlanID planID: UUID) -> FetchDescriptor<PrescriptionChange> {
        let pending = Outcome.pending
        let predicate = #Predicate<PrescriptionChange> { change in
            change.targetPlan?.id == planID && change.outcome == pending
        }
        return FetchDescriptor(predicate: predicate)
    }

    /// Changes with pending outcome targeting a specific exercise.
    static func pendingOutcome(forPlanID planID: UUID, exerciseID: UUID) -> FetchDescriptor<PrescriptionChange> {
        let pending = Outcome.pending
        let predicate = #Predicate<PrescriptionChange> { change in
            change.targetPlan?.id == planID && change.outcome == pending && change.targetExercisePrescription?.id == exerciseID
        }
        return FetchDescriptor(predicate: predicate)
    }

    /// Changes with pending outcome targeting a specific set.
    static func pendingOutcome(forPlanID planID: UUID, setID: UUID) -> FetchDescriptor<PrescriptionChange> {
        let pending = Outcome.pending
        let predicate = #Predicate<PrescriptionChange> { change in
            change.targetPlan?.id == planID && change.outcome == pending && change.targetSetPrescription?.id == setID
        }
        return FetchDescriptor(predicate: predicate)
    }

    /// All changes targeting a specific exercise in a plan.
    static func targeting(planID: UUID, exerciseID: UUID) -> FetchDescriptor<PrescriptionChange> {
        let predicate = #Predicate<PrescriptionChange> { change in
            change.targetPlan?.id == planID && change.targetExercisePrescription?.id == exerciseID
        }
        return FetchDescriptor(predicate: predicate)
    }

    /// All changes targeting a specific set in a plan.
    static func targeting(planID: UUID, setID: UUID) -> FetchDescriptor<PrescriptionChange> {
        let predicate = #Predicate<PrescriptionChange> { change in
            change.targetPlan?.id == planID && change.targetSetPrescription?.id == setID
        }
        return FetchDescriptor(predicate: predicate)
    }
}
